server:
  port: 7912

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
            
        - id: job-service-docs
          uri: lb://job-service
          predicates:
            - Path=/v3/api-docs/job-service
          filters:
            - RewritePath=/v3/api-docs/job-service, /v3/api-docs
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7911/eureka/
    fetchRegistry: true
    registerWithEureka: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: User Service API
        url: /v3/api-docs/user-service
      - name: Job Service API
        url: /v3/api-docs/job-service
